spring.datasource.url=jdbc:mysql://brad3-start.mysql.database.azure.com/mentoraai
spring.datasource.username=system_mentoraai
spring.datasource.password=SystemMentor@Ai
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

